### ISSUE TITLE
Error while php -S 127.0.0.1:8080 -t web

### ISSUE THREAD

**Issue by LUCKASSs** [ChiarilloMassimo/PokemonGo-Farm#11]
Hello guys,
I got this error when I type `php -S 127.0.0.1:8080 -t web` and when I go to `127.0.0.1:8080` in a web browser

(I'm running with this bot on Ubuntu Mate : https://github.com/PokemonGoF/PokemonGo-Bot)

```
[Tue Sep  6 17:46:27 2016] PHP Warning:  file_get_contents(/home/luca/PokemonGo-Farm/src/../app/config/parameters.json): failed to open stream: No such file or directory in /home/luca/PokemonGo-Farm/src/SilexApp.php on line 277
[Tue Sep  6 17:46:27 2016] PHP Fatal error:  Uncaught Error: Unsupported operand types in /home/luca/PokemonGo-Farm/src/SilexApp.php:282
Stack trace:
#0 /home/luca/PokemonGo-Farm/src/SilexApp.php(101): ChiarilloMassimo\PokemonGo\Farm\SilexApp->getParameters()
#1 [internal function]: ChiarilloMassimo\PokemonGo\Farm\SilexApp->registerConfigurations(Object(Silex\Application))
#2 /home/luca/PokemonGo-Farm/src/SilexApp.php(56): call_user_func(Array, Object(Silex\Application))
#3 [internal function]: ChiarilloMassimo\PokemonGo\Farm\SilexApp->ChiarilloMassimo\PokemonGo\Farm\{closure}(Array)
#4 /home/luca/PokemonGo-Farm/src/SilexApp.php(69): array_map(Object(Closure), Array)
#5 /home/luca/PokemonGo-Farm/src/SilexApp.php(42): ChiarilloMassimo\PokemonGo\Farm\SilexApp->configure(Object(Silex\Application))
#6 /home/luca/PokemonGo-Farm/web/index.php(5): ChiarilloMassimo\PokemonGo\Farm\SilexApp::getInstance()
#7 {main}
  thrown in /home/luca/PokemonGo-Farm/src/SilexApp.php on line 282
[Tue Sep  6 17:46:27 2016] 127.0.0.1:41665 [500]: / - Uncaught Error: Unsupported operand types in /home/luca/PokemonGo-Farm/src/SilexApp.php:282
Stack trace:
#0 /home/luca/PokemonGo-Farm/src/SilexApp.php(101): ChiarilloMassimo\PokemonGo\Farm\SilexApp->getParameters()
#1 [internal function]: ChiarilloMassimo\PokemonGo\Farm\SilexApp->registerConfigurations(Object(Silex\Application))
#2 /home/luca/PokemonGo-Farm/src/SilexApp.php(56): call_user_func(Array, Object(Silex\Application))
#3 [internal function]: ChiarilloMassimo\PokemonGo\Farm\SilexApp->ChiarilloMassimo\PokemonGo\Farm\{closure}(Array)
#4 /home/luca/PokemonGo-Farm/src/SilexApp.php(69): array_map(Object(Closure), Array)
#5 /home/luca/PokemonGo-Farm/src/SilexApp.php(42): ChiarilloMassimo\PokemonGo\Farm\SilexApp->configure(Object(Silex\Application))
#6 /home/luca/PokemonGo-Farm/web/index.php(5): ChiarilloMassimo\PokemonGo\Farm\SilexApp::getInstance()
#7 {main}
  thrown in /home/luca/PokemonGo-Farm/src/SilexApp.php on line 282

```

thx !

**Comment by LUCKASSs** [comment]
@ChiarilloMassimo

**Comment by massimo-me** [comment]
Please check if `app/config/parameters.json` exists.

**Comment by LUCKASSs** [comment]
@ChiarilloMassimo ok that work fine but I have 2 other questions : 

How to link the bot to the UI ? (I have this bot : https://github.com/PokemonGoF/PokemonGo-Bot)
I have already set up the bot inside PokemonGo-Farm/PokemonGo-Bot, the bot works fine but the bot doesn't link with the UI
I set the websocket to 'true' in the bot config

thx

**Comment by LUCKASSs** [comment]
@ChiarilloMassimo
